### ISSUE TITLE
Line 54 in topic "Shared Functions" have a error

### ISSUE THREAD

**Issue by EstanislauFilho** [FanchenBao/reinforcement_learning#2]
Line 54 in topic "Shared Functions" have a error in the condition: 
`if 0 <= ni < num_rows and 0 <= nj <  and grid[ni, nj] == 0:`

The correct would be...
`if 0 <= ni < num_rows and 0 <= nj < num_cols  and grid[ni, nj] == 0:`

Excellent project

**Comment by FanchenBao** [comment]
Thanks for finding the error. Which project (project 1, 2, or 3) does the error originate?

**Comment by EstanislauFilho** [comment]
Project 2

**Comment by FanchenBao** [comment]
Fixed. Thanks again!
